name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:
    env:
      docker_username: ${{secrets.DOCKER_simon_USERNAME}}
      docker_password: ${{secrets.DOCKER_simon_PASSWORD}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: docker login -u $docker_username -p $docker_password
    - name: Build the Docker image
      run: docker build -t simontroedsson/demo:1.0 .
    - name: Push image to dockerhub
      run: docker push simontroedsson/demo:1.0
