name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    env:
      username: ${{secrets.DOCKER_simon_USERNAME}}
      password: ${{secrets.DOCKER_simon_PASSWORD}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t simontroedsson/demo .
    - name: login to dockerhub
      run: docker login -u $username -p $password
    - name: Push image to dockerhub
      run: docker push simontroedsson/demo:test_image
