name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    env:
      docker_username: ${{secrets.DOCKER_simon_USERNAME}}
      docker_password: ${{secrets.DOCKER_simon_PASSWORD}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: $docker_username
        password: $docker_password
    - name: Build the Docker image
      run: docker build -t simontroedsson/demo:latest .
    - name: Push image to dockerhub
      run: docker push simontroedsson/demo:latest
