name: Docker Image CI


on:
  workflow_dispatch:
    inputs:
      run_test_job:
        description: 'Run test job'
        required: true
        type: boolean
        default: false
      run_build_deploy_image_job:
        description: 'Run build and deploy image job'
        required: True
        type: boolean
        default: false

permissions:
  contents: read

env:
  docker_username: 123
  docker_password: 123
  API_KEY: 123
  

jobs:
  test:}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: echo "The value of my_input is: ${{ github.event.inputs.my_input }}"
  
  build_deploy_image:
    runs-on: ubuntu-latest
    needs: test
   
    steps:
    - uses: actions/checkout@v4
    - name: test2
      run: echo test
