# This is a basic workflow to help you get started with Actions

name: test needs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      var1: 'hej hej'
      var2: 'hallå'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $my_secret
        
      - name: Run a one-line script
        run: echo $var1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print secret
        run: echo $my_secret
      - name: print var
        run: echo $var1
      

   
